<#
.SYNOPSIS
  PhantomClick guest-side first-boot bootstrap.

.DESCRIPTION
  Runs inside the freshly-installed Windows 11 VM after the unattended setup
  finishes. Installs Python 3.12, Git, OpenSSH server (with firewall rule),
  registers a Scheduled Task that auto-starts PhantomClick at user login,
  and detects the Arduino COM port if one is currently passed through.

  Designed to be idempotent — re-running it on an already-bootstrapped VM is
  a no-op for each step.

.NOTES
  Invoked by VBoxManage's "unattended install --post-install-template" hook.
  Logs to C:\PhantomClick-bootstrap.log so the host can scrape progress via
  SSH after the network is up.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Continue'   # log everything, don't blow up on a single step
Set-StrictMode -Version Latest

$LogPath  = 'C:\PhantomClick-bootstrap.log'
$RepoDir  = 'C:\PhantomClick'
$TaskName = 'PhantomClickBot'

function Log([string]$Msg) {
    $ts = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    "$ts  $Msg" | Tee-Object -FilePath $LogPath -Append
}

Log "==> Bootstrap starting"

# -- 1. Repo placeholder ---------------------------------------------------
if (-not (Test-Path $RepoDir)) {
    New-Item -ItemType Directory -Force -Path $RepoDir | Out-Null
    Log "Created $RepoDir (empty until first 'phantom-vm.ps1 sync' from host)"
}

# -- 2. Winget availability ------------------------------------------------
$winget = Get-Command winget.exe -ErrorAction SilentlyContinue
if (-not $winget) {
    Log "WARN winget not yet available; will retry once App Installer registers."
    # On fresh Win11, App Installer (winget host) sometimes lags by a few minutes
    # post-OOBE. Wait briefly.
    1..6 | ForEach-Object {
        Start-Sleep -Seconds 30
        $winget = Get-Command winget.exe -ErrorAction SilentlyContinue
        if ($winget) { break }
    }
}

# -- 3. Python 3.12 --------------------------------------------------------
$python = Get-Command python.exe -ErrorAction SilentlyContinue
if (-not $python) {
    if ($winget) {
        Log "Installing Python 3.12 via winget"
        winget install --id Python.Python.3.12 -e --silent --accept-source-agreements --accept-package-agreements 2>&1 | Tee-Object -FilePath $LogPath -Append
    } else {
        Log "ERROR no winget; install Python 3.12 manually from python.org"
    }
} else {
    Log "Python already present: $((& python.exe --version) 2>&1)"
}

# -- 4. Git ---------------------------------------------------------------
$git = Get-Command git.exe -ErrorAction SilentlyContinue
if (-not $git -and $winget) {
    Log "Installing Git via winget"
    winget install --id Git.Git -e --silent --accept-source-agreements --accept-package-agreements 2>&1 | Tee-Object -FilePath $LogPath -Append
}

# -- 5. OpenSSH Server ----------------------------------------------------
# OpenSSH is built into Win10/11 since 2018 — installed via Add-WindowsCapability.
$sshCap = Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH.Server*'
if ($sshCap -and $sshCap.State -ne 'Installed') {
    Log "Installing OpenSSH Server"
    Add-WindowsCapability -Online -Name $sshCap.Name 2>&1 | Tee-Object -FilePath $LogPath -Append
}
Log "Starting + enabling sshd service"
Start-Service sshd -ErrorAction SilentlyContinue
Set-Service -Name sshd -StartupType Automatic -ErrorAction SilentlyContinue

# Firewall: allow SSH inbound on private + public profiles. Win11's default
# rule "OpenSSH-Server-In-TCP" exists post-install; ensure it's enabled.
$rule = Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue
if ($rule) {
    Enable-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue | Out-Null
} else {
    New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
        -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -Profile Any | Out-Null
}

# -- 6. PhantomClick PowerShell launcher (referenced by Task Scheduler) ---
$launcher = "$RepoDir\.bot-run.ps1"
@'
# Auto-generated by PhantomBox bootstrap. Restarts on crash.
$ErrorActionPreference = 'Continue'
Set-Location 'C:\PhantomClick'

# First-run dependency install. Cached via .deps-installed flag so this is
# fast on subsequent boots.
if (-not (Test-Path '.deps-installed') -and (Test-Path 'requirements.txt')) {
    Write-Host "Installing dependencies (first run)..."
    & python.exe -m pip install --upgrade pip
    & python.exe -m pip install -r requirements.txt
    & python.exe -m pip install pyserial    # not in requirements by default; needed for Arduino
    Set-Content -Path '.deps-installed' -Value (Get-Date).ToString('o')
}

# Restart-loop wrapper. If the bot crashes, wait 10s and respawn — keeps the
# Monitor tab reachable even after a transient failure.
while ($true) {
    & python.exe main.py
    Start-Sleep -Seconds 10
}
'@ | Set-Content -Path $launcher -Encoding UTF8 -Force
Log "Wrote launcher $launcher"

# -- 7. Scheduled Task: auto-start at user login --------------------------
$existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existingTask) {
    Log "Task '$TaskName' already exists; leaving alone (use Unregister-ScheduledTask to recreate)."
} else {
    Log "Registering Scheduled Task '$TaskName'"
    $action  = New-ScheduledTaskAction -Execute 'powershell.exe' `
        -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$launcher`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1)
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Settings $settings -RunLevel Limited -User $env:USERNAME 2>&1 | Tee-Object -FilePath $LogPath -Append
}

# -- 8. Arduino COM port detection ---------------------------------------
# Only meaningful if the Arduino is plugged in already and pyserial is present.
# We try once; if pyserial isn't installed yet, the launcher's first run will
# install it and the user can run 'phantom-vm.ps1 com-port' afterwards.
try {
    $ports = & python.exe -c "import serial.tools.list_ports as p; print(';'.join(x.device for x in p.comports() if (x.vid==0x2341)))" 2>$null
    if ($ports) {
        $first = ($ports.Split(';') | Where-Object { $_ })[0]
        if ($first -and (Test-Path "$RepoDir\config.json")) {
            $cfg = Get-Content "$RepoDir\config.json" -Raw | ConvertFrom-Json
            $cfg.serial_hid_port = $first
            $cfg | ConvertTo-Json -Depth 10 | Set-Content "$RepoDir\config.json" -Encoding UTF8
            Log "Wrote serial_hid_port=$first to config.json"
        } else {
            Log "Arduino at $first detected; config.json not yet present (will be created at first sync)."
        }
    } else {
        Log "No Arduino visible yet (no VID 0x2341 device). Plug it in or check VBox USB filter."
    }
} catch {
    Log "COM detection skipped (pyserial not yet installed): $_"
}

# -- 9. Marker for the host's status command ------------------------------
Set-Content -Path 'C:\PhantomClick-bootstrap.done' -Value (Get-Date).ToString('o') -Force
Log "==> Bootstrap complete"
